### ISSUE TITLE
CTRL-C Doesn't kill all containers when in dev mode

### ISSUE THREAD

**Issue by hawknewton** [constantcontact/bigrig#1]
If a container is added in the dev profile hitting CTRL-C doesn't kill it.  Similarly, you don't get log output from it either.

The issue stems from the fact that each action takes the file as a parameter, not the parsed `Descriptor` object.  We should refactor the actions to take the parsed `Descriptor` object with the activated profiles already overlayed.

As a bonus, we get to add -p flags to all commands pretty easily.

**Comment by sinangedik** [comment]
Resolved with #4. Closing.
